mode: standalone
replicas: 1

auth:
  existingSecret: "minio"
  rootUserSecretKey: "root-user"
  rootPasswordSecretKey: "root-password"

persistence:
  enabled: true
  size: 10Gi
  storageClass: "local-path"
  accessModes:
    - ReadWriteOnce

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m

ingress:
  enabled: true
  ingressClassName: "nginx"
  pathType: ImplementationSpecific
  hosts:
    - minio.yqzc.dski23a.timebertt.dev
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  tls:
    - secretName: minio-tls-cert
      hosts:
        - minio.yqzc.dski23a.timebertt.dev

# DEAKTIVIEREN, um den Webhook-Konflikt zu l√∂sen
consoleIngress:
  enabled: false

buckets: []