# Grundmodus
mode: standalone
replicas: 1

# Authentifizierung
auth:
  existingSecret: "minio"
  rootUserSecretKey: "root-user"
  rootPasswordSecretKey: "root-password"

# Persistence
persistence:
  enabled: true
  size: 10Gi
  storageClass: "local-path"
  accessModes:
    - ReadWriteOnce

# Ressourcen-Limits
resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m

# Ingress Konfiguration
ingress:
  enabled: true
  ingressClassName: "nginx"
  path: /
  hosts:
    - minio.yqzc.dski23a.timebertt.dev
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    # Optional: Falls MinIO SSL-Redirects erzwingen soll
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - secretName: minio-tls-cert
      hosts:
        - minio.yqzc.dski23a.timebertt.dev

buckets: []